artifacts_root: artifacts #main folder where all output store

data_ingestion:
 root_dir: artifacts/data_ingestion                        # data ingestion folder
 source_url: https://github.com/mayurkadam9833/Datasets/raw/refs/heads/main/bank_full.zip # link for download data
 local_data_file: artifacts/data_ingestion/bank_full.zip   # downloaded data store path
 unzip_dir: artifacts/data_ingestion                       # exract file data path

data_validation:
 root_dir: artifacts/data_validation                          # data validation folder
 unzip_data: artifacts/data_ingestion/bank_full.csv           # unzip data file path from data ingestion
 STATUS_FILE: artifacts/data_validation/validation_status.txt # data validation txt file path  

data_transformation:
 root_dir: artifacts/data_transformation                      # data transformation folder
 data_path: artifacts/data_ingestion/bank_full.csv            # extract data path 


model_trainer:
 root_dir: artifacts/model_trainer                            # model trainer folder
 train_data_path: artifacts/data_transformation/Train.csv     # Train data path
 model_name: model.joblib                                     # saved model path
 
model_evaluation:
 root_dir: artifacts/model_evaluation                         # model evaluation folder
 test_data_path: artifacts/data_transformation/Test.csv       # test data path
 model_path: artifacts/model_trainer/model.joblib             # trained model path
 evaluation_file: artifacts/model_evaluation/metrics.json     # metric file path